# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres:14.1-alpine
    hostname: myhome
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes: 
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - .:/opt/home
volumes:
  db:
    driver: local
